version: '3.3'
services:
  database:
    container_name: mafia_panels_database
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'mysql'
    volumes:
      - './docker/mysql-data/db:/var/lib/mysql'
    ports:
      - '3306:3306'
  php:
    container_name: mafia_panels_php
    build:
      context: ./docker/php/
    ports:
      - '9006:9000'
    volumes:
      - ./:/var/www/backend
    depends_on:
      - database
  nginx:
    container_name: mafia_panels_nginx
    build:
      context: ./docker/nginx/
    ports:
      - '8086:80'
    volumes:
      - ./:/var/www/backend
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
